name: vcfgenerator_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - bwa=0.7.18
  - samtools=1.21
  - bcftools=1.21
  - sra-tools=3.1.1
  - entrez-direct=22.4
  - ncbi-datasets-cli=16.41.0
  - snpeff=5.2
  - openjdk=11
  - fastqc=0.12.1
  - trimmomatic=0.39
  - pip
  - pip:
    - pandas==2.2.2
    - numpy==2.0.0
