name: vcfgenerator_env
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.11
  - entrez-direct=22.4
  - ncbi-datasets-cli=16.41.0
  - sra-tools=3.4.1
  - trimmomatic=0.39
  - fastqc=0.12.1
  - bwa=0.7.18
  - samtools=1.21
  - bcftools=1.21
  - snpeff=5.2
  - openjdk=11
  - pip
  - r-base=4.3.3
  - r-tidyverse=2.0.0
  - r-data.table=1.15.4
  - r-stringr=1.5.1
  - r-biocmanager=1.30.22
  - r-circlize=0.4.16
