#!/bin/bash
#LloydJonesIII


## Grab metadata using the esearch list 

prefetch --option-file pH.txt -O ../../media/volume/sdb/sra/pH/
# ph will be changed to project name for the users search

## takes list generated by esearch to grab the desired fastq files from the databases

fasterq-dump --outdir ../../media/volume/sdb/sra/pH/fastq/ ../../media/volume/sdb/sra/pH/SRR*
# ph will be changed to project name for the users search
# output = ../../media/volume/sdb/sra/pH/fastq/
# input = ../../media/volume/sdb/sra/pH/SRR*

## gzip all fastq files that were collected 

gzip *.fastq
#reduces storage cost of all collected fastq files by making them zip files 
